# Generated by Django 4.2.6 on 2023-10-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_personal', '0002_alter_personal_apellidos_alter_personal_nombres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='rol',
            field=models.CharField(blank=True, choices=[('ayudante', 'Ayudante'), ('chofer', 'Chofer')], max_length=256, verbose_name='Rol'),
        ),
    ]
