# Generated by Django 4.2.6 on 2023-11-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_personal', '0003_personal_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='rol',
            field=models.CharField(blank=True, choices=[('Ayudante', 'Ayudante'), ('Chofer', 'Chofer')], max_length=256, verbose_name='Rol'),
        ),
    ]
