# Generated by Django 4.2.5 on 2023-11-13 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_personal', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_bus', models.CharField(blank=True, choices=[('Microbus', 'Microbus'), ('Coaster', 'Coaster')], max_length=256, verbose_name='Tipo de Autobus')),
                ('numero_placa', models.CharField(blank=True, max_length=256, verbose_name='No. de placa')),
                ('codigo_bus', models.CharField(blank=True, max_length=256, verbose_name='Codigo Bus')),
                ('horario_salida', models.CharField(blank=True, max_length=256, verbose_name='Horario Salida')),
                ('ayudante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses_ayudante', to='modulo_personal.personal', verbose_name='Ayudante')),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses_chofer', to='modulo_personal.personal', verbose_name='Chofer')),
            ],
        ),
    ]
