# Generated by Django 4.2.5 on 2023-10-17 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=256)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=256, verbose_name='Numero de placa')),
                ('ultima_fecha_rotacion', models.DateField(verbose_name='Ultima fecha de rotación')),
                ('tipo_bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modulo_buses.tipobus')),
            ],
        ),
    ]
