# Generated by Django 4.2.5 on 2023-10-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_buses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField()),
                ('NumeroApro', models.IntegerField()),
                ('PasajeApro', models.IntegerField()),
                ('idBus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modulo_buses.bus')),
            ],
        ),
    ]
