# Generated by Django 4.2.5 on 2023-10-26 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_buses', '0002_registrobus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='tipo_bus',
        ),
        migrations.DeleteModel(
            name='TipoBus',
        ),
    ]
