# Generated by Django 4.2.5 on 2023-10-26 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_buses', '0003_remove_bus_tipo_bus_delete_tipobus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('coban', 'Coban'), ('carcha', 'Carcha')], max_length=256, verbose_name='Origen Bus')),
                ('cantidad_per', models.IntegerField(verbose_name='Cantidad de Pasajeros')),
                ('pasaje', models.DecimalField(decimal_places=3, max_digits=50, verbose_name='Cantidad de Pasaje')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
            ],
        ),
        migrations.RemoveField(
            model_name='bus',
            name='placa',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='ultima_fecha_rotacion',
        ),
        migrations.AddField(
            model_name='bus',
            name='capacidad',
            field=models.IntegerField(default=0, verbose_name='Capacidad'),
        ),
        migrations.AddField(
            model_name='bus',
            name='color',
            field=models.CharField(default='Sin color', max_length=256, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='bus',
            name='marca',
            field=models.CharField(blank=True, max_length=256, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='bus',
            name='modelo',
            field=models.CharField(blank=True, max_length=256, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='bus',
            name='numero_placa',
            field=models.CharField(default='Sin Placa', max_length=256, verbose_name='No. de placa'),
        ),
        migrations.AddField(
            model_name='bus',
            name='tipo_bus',
            field=models.CharField(blank=True, choices=[('microbus', 'Microbus'), ('coaster', 'Coaster')], max_length=256, verbose_name='Tipo de Autobus'),
        ),
        migrations.DeleteModel(
            name='RegistroBus',
        ),
        migrations.AddField(
            model_name='registro',
            name='idBus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modulo_buses.bus'),
        ),
    ]
