# Generated by Django 4.2.6 on 2023-10-30 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_personal', '0003_personal_rol'),
        ('modulo_buses', '0004_registro_remove_bus_placa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='color',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='modelo',
        ),
        migrations.AddField(
            model_name='bus',
            name='ayudante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses_ayudante', to='modulo_personal.personal', verbose_name='Ayudante'),
        ),
        migrations.AddField(
            model_name='bus',
            name='chofer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses_chofer', to='modulo_personal.personal', verbose_name='Chofer'),
        ),
        migrations.AddField(
            model_name='bus',
            name='codigo_bus',
            field=models.CharField(blank=True, max_length=256, verbose_name='Codigo Bus'),
        ),
        migrations.AddField(
            model_name='bus',
            name='horario_salida',
            field=models.CharField(blank=True, max_length=256, verbose_name='Horario Salida'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='numero_placa',
            field=models.CharField(blank=True, max_length=256, verbose_name='No. de placa'),
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
