# Generated by Django 4.2.5 on 2023-10-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='apellidos',
            field=models.CharField(blank=True, max_length=256, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='nombres',
            field=models.CharField(blank=True, max_length=256, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='telefono',
            field=models.CharField(max_length=8, unique=True, verbose_name='Telefono'),
        ),
    ]
